---
- hosts: local
  tasks:
    - name: Generate configuration file
      template: src=/home/mbanerjee/week5/exercise1/ANSIBLE/src/access_switch.j2.multiple.items
                  dest=/home/mbanerjee/week5/exercise1/ANSIBLE/dest/{{item.hostname}}.txt  
      with_items:
        - {hostname: switch-1, ip_addr: 1.1.1.1}
        - {hostname: switch-2, ip_addr: 1.1.2.1}
        - {hostname: switch-3, ip_addr: 1.1.3.1}
        - {hostname: switch-4, ip_addr: 1.1.4.1}
  
