---


- name: Arista-Ansible Exercise1
  hosts: arista

  tasks:
    - name: Settign Ethernet6 description 
      eos_interface: name=Ethernet6 description="***IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Setting Ethernet6 to access mode vlan333 
      eos_switchport: name={{ item }} mode=access access_vlan=333 
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - Ethernet6
