---


- name: Arista-Ansible Exercise4 Cleanup
  hosts: arista

  tasks:
    - name: Configure Ethernet6 to default cleanup
      eos_switchport: name=Ethernet6 mode=access access_vlan=1 trunk_allowed_vlans=1-4094
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Setting Ethernet6 description to none 
      eos_interface: name=Ethernet6 description=""
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Remove VLANs
      eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }} state=absent
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
      with_items:
        - {vlan_name: mb1, vlan_id: 333}
        - {vlan_name: mb2, vlan_id: 334}

