---


- name: Arista-Ansible Exercise1
  hosts: arista

  tasks:
    - name: Configure Ethernet6 to trunk
      eos_switchport: name=Ethernet6 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=333,334
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
